services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    # Piston needs these to create the 'sandboxes' for the code it runs
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - ./piston_packages:/piston/packages
    tmpfs:
      - /tmp:exec